name: main

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.2'
        
    - name: Test Case 1 - Multiple Numbers
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
        diff test1_output.txt test_data/test1_expected.txt
    - name: Print Test Case 1 Output
      run: cat test1_output.txt
        
    - name: Test Case 2 - Single Number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
        diff test2_output.txt test_data/test2_expected.txt
    - name: Print Test Case 2 Output
      run: cat test2_output.txt

    - name: Test Case 3 - Blank File
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
        diff test3_output.txt test_data/test3_expected.txt
    - name: Print Test Case 3 Output
      run: cat test3_output.txt
